# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #端口配置
  port: 8086
  #连接超时时间
  connection-timeout: 5000ms
  servlet:
    #映射项目路径
    context-path: /

spring:
  profiles:
    # 环境 开发dev，测试test，生产prod
    active: dev
  jackson:
    serialization:
      # jackson返回时间戳
      write-dates-as-timestamps: true

